name: Go
on: push
env:
  GO111MODULE: on
  GOPATH: /home/runner/go
jobs:
  build:
    runs-on: ubuntu-latest
    name: Go ${{ matrix.go }}
    strategy:
      matrix:
        go:
        - '1.21.x'
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - run: go test -cover -race ./...
